Welcome to the unofficial DiamondFire Manual! This site is automatically generated by DiamondFire's <a href="https://diamondfire.miraheze.org/wiki/Actiondump">actiondump</a>

<h2>Sections</h2>
<a href='/man/codeblock'><h3>Code Blocks</h3></a>